<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCSLyXa1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCSLyXa1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCSLyXa1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCSLyXa1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCSLyXa1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CSLyXa1',
    'container.build_id' => 'd5b44dc6',
    'container.build_time' => 1571933158,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCSLyXa1');
