<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.VvqefaD' shared service.

return $this->privates['.service_locator.VvqefaD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ApiGenreController::create' => ['privates', '.service_locator.uMflkEJ', 'get_ServiceLocator_UMflkEJService.php', true],
    'App\\Controller\\ApiGenreController::delete' => ['privates', '.service_locator.6qBR3cr', 'get_ServiceLocator_6qBR3crService.php', true],
    'App\\Controller\\ApiGenreController::edit' => ['privates', '.service_locator.uMflkEJ', 'get_ServiceLocator_UMflkEJService.php', true],
    'App\\Controller\\ApiGenreController::list' => ['privates', '.service_locator.qaoVO5q', 'get_ServiceLocator_QaoVO5qService.php', true],
    'App\\Controller\\ApiGenreController::show' => ['privates', '.service_locator.Fg1zQj6', 'get_ServiceLocator_Fg1zQj6Service.php', true],
    'App\\Controller\\ApiGenreController:create' => ['privates', '.service_locator.uMflkEJ', 'get_ServiceLocator_UMflkEJService.php', true],
    'App\\Controller\\ApiGenreController:delete' => ['privates', '.service_locator.6qBR3cr', 'get_ServiceLocator_6qBR3crService.php', true],
    'App\\Controller\\ApiGenreController:edit' => ['privates', '.service_locator.uMflkEJ', 'get_ServiceLocator_UMflkEJService.php', true],
    'App\\Controller\\ApiGenreController:list' => ['privates', '.service_locator.qaoVO5q', 'get_ServiceLocator_QaoVO5qService.php', true],
    'App\\Controller\\ApiGenreController:show' => ['privates', '.service_locator.Fg1zQj6', 'get_ServiceLocator_Fg1zQj6Service.php', true],
], [
    'App\\Controller\\ApiGenreController::create' => '?',
    'App\\Controller\\ApiGenreController::delete' => '?',
    'App\\Controller\\ApiGenreController::edit' => '?',
    'App\\Controller\\ApiGenreController::list' => '?',
    'App\\Controller\\ApiGenreController::show' => '?',
    'App\\Controller\\ApiGenreController:create' => '?',
    'App\\Controller\\ApiGenreController:delete' => '?',
    'App\\Controller\\ApiGenreController:edit' => '?',
    'App\\Controller\\ApiGenreController:list' => '?',
    'App\\Controller\\ApiGenreController:show' => '?',
]);
