<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Fg1zQj6' shared service.

return $this->privates['.service_locator.Fg1zQj6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'genre' => ['privates', '.errored..service_locator.Fg1zQj6.App\\Entity\\Genre', NULL, 'Cannot autowire service ".service_locator.Fg1zQj6": it references class "App\\Entity\\Genre" but no such service exists.'],
    'serializer' => ['services', 'serializer', 'getSerializerService.php', true],
], [
    'genre' => 'App\\Entity\\Genre',
    'serializer' => '?',
]);
